const { onCall, HttpsError } = require('firebase-functions/v2/https');
const admin = require('firebase-admin');
const db = admin.firestore();
const FV = admin.firestore.FieldValue;
function assertAdmin(request){if(!request.auth?.uid)throw new HttpsError('unauthenticated','É necessário iniciar sessão.');return request.auth.uid;}
async function isAdmin(uid){const s=await db.collection('users').doc(uid).get();return s.exists&&s.data()?.role==='admin';}
async function audit(uid,action,target={}){await db.collection('admin_audit_logs').add({adminUid:uid,action,target,createdAt:FV.serverTimestamp()});}
async function notify(uid,titulo,mensagem,tipo,adminUid){if(!uid)return;await db.collection('notificacoes').doc(uid).collection('items').add({titulo,mensagem,tipo:tipo||'info',lida:false,enviadoEm:FV.serverTimestamp(),enviadoPor:adminUid,isAdmin:true});}
exports.adminOperation=onCall({enforceAppCheck:false},async(request)=>{const adminUid=assertAdmin(request);if(!(await isAdmin(adminUid)))throw new HttpsError('permission-denied','Apenas administradores podem executar esta operação.');const {action,payload={}}=request.data||{};try{switch(action){
case 'verifyUser':{const {uid}=payload;if(!uid)throw new HttpsError('invalid-argument','UID obrigatório.');await db.collection('users').doc(uid).set({verificado:true,isVerified:true,contaVerificada:true,verificadoEm:FV.serverTimestamp(),verificadoPor:adminUid,verificacaoEstado:'aprovado',status:'activo',accountStatus:'activo',contaEstado:{estado:'ativa'}},{merge:true});await audit(adminUid,action,{uid});return {ok:true};}
case 'setUserStatus':{const {uid,status,motivo,dias,notificar=true}=payload;if(!uid||!['activo','suspenso','banido'].includes(status))throw new HttpsError('invalid-argument','UID ou status inválido.');const banned=status==='banido',suspended=status==='suspenso';const data={status,accountStatus:banned?'banned':suspended?'suspended':'active',userStatus:banned?'banned':suspended?'suspended':'active',suspended,banned,blocked:banned,statusMotivo:motivo||null,suspensionReason:suspended?(motivo||null):null,banReason:banned?(motivo||null):null,statusActualizadoEm:FV.serverTimestamp(),statusActualizadoPor:adminUid,contaEstado:{estado:banned?'banida':suspended?'suspensa':'ativa',motivo:motivo||null}};if(suspended&&Number(dias)>0){const exp=new Date();exp.setDate(exp.getDate()+Number(dias));data.suspensaoExpira=exp;}else if(!suspended)data.suspensaoExpira=null;await db.collection('users').doc(uid).set(data,{merge:true});if(notificar)await notify(uid,banned?'Conta banida':suspended?'Conta suspensa':'Conta reactivada',motivo||'O estado da tua conta foi actualizado pelo administrador.',banned||suspended?'alerta':'sucesso',adminUid);await audit(adminUid,action,{uid});return {ok:true};}
case 'deleteUser':{const {uid}=payload;if(!uid||uid===adminUid)throw new HttpsError('failed-precondition','Não é permitido eliminar a própria conta administrativa.');await db.collection('users').doc(uid).delete();try{await admin.auth().deleteUser(uid);}catch(e){if(e.code!=='auth/user-not-found')throw e;}await audit(adminUid,action,{uid});return {ok:true};}
case 'deletePost':{const {id}=payload;if(!id)throw new HttpsError('invalid-argument','ID obrigatório.');await db.collection('posts').doc(id).delete();await audit(adminUid,action,{postId:id});return {ok:true};}
case 'updatePostModeration':{const {id,oculto,destacado}=payload;if(!id)throw new HttpsError('invalid-argument','ID obrigatório.');const d={moderadoEm:FV.serverTimestamp(),moderadoPor:adminUid};if(oculto!==undefined)Object.assign(d,{oculto:!!oculto,hidden:!!oculto,visible:!oculto});if(destacado!==undefined)Object.assign(d,{destacado:!!destacado,featured:!!destacado});await db.collection('posts').doc(id).set(d,{merge:true});await audit(adminUid,action,{postId:id});return {ok:true};}
case 'deleteStory':{const {id}=payload;if(!id)throw new HttpsError('invalid-argument','ID obrigatório.');await db.collection('stories').doc(id).delete();await audit(adminUid,action,{storyId:id});return {ok:true};}
case 'resolveReport':case 'ignoreReport':{const {id,collection='denuncias'}=payload;if(!id||!['denuncias','reports'].includes(collection))throw new HttpsError('invalid-argument','Denúncia inválida.');await db.collection(collection).doc(id).set({status:action==='resolveReport'?'resolvido':'ignorado',resolvidoEm:FV.serverTimestamp(),resolvidoPor:adminUid},{merge:true});await audit(adminUid,action,{collection,id});return {ok:true};}
case 'deleteReportedContent':{const {reportId,reportCollection='reports',postId}=payload;if(!reportId||!postId)throw new HttpsError('invalid-argument','IDs obrigatórios.');await db.collection('posts').doc(postId).delete();if(['reports','denuncias'].includes(reportCollection))await db.collection(reportCollection).doc(reportId).set({status:'resolvido',conteudoEliminado:true,resolvidoEm:FV.serverTimestamp(),resolvidoPor:adminUid},{merge:true});await audit(adminUid,action,{reportId,postId});return {ok:true};}
case 'setPaymentStatus':{const {id,status}=payload;if(!id||!['confirmado','recusado','pendente'].includes(status))throw new HttpsError('invalid-argument','Pagamento inválido.');const ref=db.collection('payments').doc(id),snap=await ref.get();if(!snap.exists)throw new HttpsError('not-found','Pagamento não encontrado.');const p=snap.data();await ref.set({status,...(status==='confirmado'?{confirmadoEm:FV.serverTimestamp(),confirmadoPor:adminUid}:{recusadoEm:FV.serverTimestamp(),recusadoPor:adminUid})},{merge:true});if(status==='confirmado'){const uid=p.utilizadorId||p.userId;if(uid){const plano=p.plano||p.plan||'pro';await db.collection('users').doc(uid).set({plano,plan:plano,subscriptionPlan:plano,subscriptionStatus:'active',subscriptionStartDate:FV.serverTimestamp()},{merge:true});}}await audit(adminUid,action,{paymentId:id});return {ok:true};}
case 'assignPlan':{const {uid,plano,duracao,motivo,valor}=payload;if(!uid||!plano)throw new HttpsError('invalid-argument','Utilizador e plano são obrigatórios.');await db.collection('users').doc(uid).set({plano,plan:plano,subscriptionPlan:plano,subscriptionStatus:'active',planoAtribuido:FV.serverTimestamp(),planoDuracao:duracao||null,planoMotivo:motivo||null},{merge:true});if(Number(valor)>0)await db.collection('payments').add({utilizadorId:uid,plano,valor:Number(valor),metodo:'Admin',status:'confirmado',motivo:motivo||null,timestamp:FV.serverTimestamp(),criadoPor:adminUid});await audit(adminUid,action,{uid},{plano});return {ok:true};}
case 'resolveSupport':{const {id}=payload;if(!id)throw new HttpsError('invalid-argument','Ticket obrigatório.');await db.collection('suporte').doc(id).set({status:'resolvido',resolvidoEm:FV.serverTimestamp(),resolvidoPor:adminUid},{merge:true});await audit(adminUid,action,{id});return {ok:true};}
case 'setProfessionalVerification':case 'setProfessionalMonetization':case 'disableProfessional':{const {uid}=payload;if(!uid)throw new HttpsError('invalid-argument','UID obrigatório.');const d=action==='setProfessionalVerification'?{verificado:true,verificadoEm:FV.serverTimestamp(),verificadoPor:adminUid}:action==='setProfessionalMonetization'?{monetizado:true,monetizadoEm:FV.serverTimestamp(),monetizadoPor:adminUid}:{ativo:false,desativadoEm:FV.serverTimestamp(),desativadoPor:adminUid};await db.collection('users').doc(uid).collection('perfis').doc('profissional').set(d,{merge:true});if(action==='setProfessionalVerification')await db.collection('users').doc(uid).set({contaVerificada:true},{merge:true});if(action==='disableProfessional')await db.collection('users').doc(uid).set({modoProfissional:false},{merge:true});await audit(adminUid,action,{uid});return {ok:true};}
case 'savePlatformConfig':case 'saveLimitsConfig':case 'saveSecurityConfig':{const {data}=payload;if(!data)throw new HttpsError('invalid-argument','Configuração inválida.');const id=action==='savePlatformConfig'?'plataforma':action==='saveLimitsConfig'?'limites':'seguranca';await db.collection('configuracoes').doc(id).set({...data,atualizadoEm:FV.serverTimestamp(),updatedBy:adminUid},{merge:true});await audit(adminUid,action,{docId:id});return {ok:true};}
case 'setMaintenance':{await db.collection('configuracoes').doc('plataforma').set({manutencao:!!payload.ativo,maintenanceMode:!!payload.ativo,atualizadoEm:FV.serverTimestamp(),updatedBy:adminUid},{merge:true});await audit(adminUid,action,{},payload);return {ok:true};}
case 'savePlan':{const {id,data}=payload;if(!id||!data)throw new HttpsError('invalid-argument','Plano inválido.');await db.collection('planos').doc(id).set({...data,atualizadoEm:FV.serverTimestamp(),atualizadoPor:adminUid},{merge:true});await audit(adminUid,action,{planId:id});return {ok:true};}
case 'setPlanActive':{const {id,ativo}=payload;if(!id)throw new HttpsError('invalid-argument','Plano inválido.');await db.collection('planos').doc(id).set({ativo:!!ativo,atualizadoEm:FV.serverTimestamp(),atualizadoPor:adminUid},{merge:true});await audit(adminUid,action,{planId:id});return {ok:true};}
case 'sendNotification':{const {uids,titulo,mensagem,tipo='info'}=payload;if(!Array.isArray(uids)||!uids.length||!titulo||!mensagem)throw new HttpsError('invalid-argument','Destinatários, título e mensagem são obrigatórios.');for(let i=0;i<uids.length;i+=450){const b=db.batch();uids.slice(i,i+450).forEach(uid=>b.set(db.collection('notificacoes').doc(uid).collection('items').doc(),{titulo,mensagem,tipo,lida:false,enviadoEm:FV.serverTimestamp(),enviadoPor:adminUid,isAdmin:true}));await b.commit();}await audit(adminUid,action,{recipients:uids.length});return {ok:true,count:uids.length};}
case 'deleteChat':{const {id}=payload;if(!id)throw new HttpsError('invalid-argument','Chat obrigatório.');await db.recursiveDelete(db.collection('chats').doc(id));await audit(adminUid,action,{chatId:id});return {ok:true};}
case 'endCall':{const {id}=payload;if(!id)throw new HttpsError('invalid-argument','Chamada obrigatória.');await db.collection('chamadas').doc(id).set({estado:'terminada',terminadaPorAdmin:adminUid,terminadaEm:FV.serverTimestamp()},{merge:true});await audit(adminUid,action,{callId:id});return {ok:true};}
case 'closeRoom':{const {id}=payload;if(!id)throw new HttpsError('invalid-argument','Sala obrigatória.');await db.collection('salas').doc(id).set({ativa:false,fechadaPorAdmin:adminUid,fechadaEm:FV.serverTimestamp()},{merge:true});await audit(adminUid,action,{roomId:id});return {ok:true};}
default:throw new HttpsError('permission-denied','Operação administrativa não permitida.');}}catch(e){console.error('[adminOperation]',action,e);if(e instanceof HttpsError)throw e;throw new HttpsError('internal','Não foi possível concluir a operação administrativa.');}});
